name: deepfeatures_20250605
channels:
  - conda-forge
dependencies:
  - _openmp_mutex
  - adlfs
  - affine
  - aiobotocore
  - aiohappyeyeballs
  - aiohttp
  - aioitertools
  - aiosignal
  - alsa-lib
  - altair
  - annotated-types
  - aom
  - appdirs
  - asciitree
  - asttokens
  - attr
  - attrs
  - aws-c-auth
  - aws-c-cal
  - aws-c-common
  - aws-c-compression
  - aws-c-event-stream
  - aws-c-http
  - aws-c-io
  - aws-c-mqtt
  - aws-c-s3
  - aws-c-sdkutils
  - aws-checksums
  - aws-crt-cpp
  - aws-sdk-cpp
  - azure-core
  - azure-core-cpp
  - azure-datalake-store
  - azure-identity
  - azure-identity-cpp
  - azure-storage-blob
  - azure-storage-blobs-cpp
  - azure-storage-common-cpp
  - azure-storage-files-datalake-cpp
  - backports
  - backports.tarfile
  - beautifulsoup4
  - binutils
  - binutils_impl_linux-64
  - binutils_linux-64
  - blinker
  - blosc
  - bokeh
  - boltons
  - boto3
  - botocore
  - branca
  - brotli
  - brotli-bin
  - brotli-python
  - brunsli
  - bzip2
  - c-ares
  - c-blosc2
  - c-compiler
  - ca-certificates
  - cachecontrol
  - cachecontrol-with-filecache
  - cached-property
  - cached_property
  - cachetools
  - cairo
  - cdsapi
  - certifi
  - cffi
  - cftime
  - charls
  - charset-normalizer
  - chartlets
  - click
  - click-default-group
  - click-plugins
  - cligj
  - cloudpickle
  - cmocean
  - colorama
  - colorspacious
  - comm
  - conda-lock
  - contourpy
  - cpython
  - crashtest
  - cryptography
  - cubo
  - cuda
  - cuda-cccl_linux-64
  - cuda-command-line-tools
  - cuda-compiler
  - cuda-crt-dev_linux-64
  - cuda-crt-tools
  - cuda-cudart
  - cuda-cudart-dev
  - cuda-cudart-dev_linux-64
  - cuda-cudart-static
  - cuda-cudart-static_linux-64
  - cuda-cudart_linux-64
  - cuda-cuobjdump
  - cuda-cupti
  - cuda-cupti-dev
  - cuda-cuxxfilt
  - cuda-driver-dev
  - cuda-driver-dev_linux-64
  - cuda-gdb
  - cuda-libraries
  - cuda-libraries-dev
  - cuda-nsight
  - cuda-nvcc
  - cuda-nvcc-dev_linux-64
  - cuda-nvcc-impl
  - cuda-nvcc-tools
  - cuda-nvcc_linux-64
  - cuda-nvdisasm
  - cuda-nvml-dev
  - cuda-nvprof
  - cuda-nvprune
  - cuda-nvrtc
  - cuda-nvrtc-dev
  - cuda-nvtx
  - cuda-nvvm-dev_linux-64
  - cuda-nvvm-impl
  - cuda-nvvm-tools
  - cuda-nvvp
  - cuda-opencl
  - cuda-opencl-dev
  - cuda-profiler-api
  - cuda-runtime
  - cuda-sanitizer-api
  - cuda-toolkit
  - cuda-tools
  - cuda-version
  - cuda-visual-tools
  - cudnn
  - cxx-compiler
  - cycler
  - cyrus-sasl
  - cytoolz
  - dask
  - dask-core
  - dask-image
  - dav1d
  - dbus
  - debugpy
  - decorator
  - deprecated
  - distlib
  - distributed
  - double-conversion
  - dulwich
  - earthengine-api
  - ecmwf-datastores-client
  - ee_extra
  - eemont
  - ensureconda
  - exceptiongroup
  - executing
  - fasteners
  - filelock
  - fiona
  - folium
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - fonttools
  - freetype
  - freexl
  - frozenlist
  - fsspec
  - gcc
  - gcc_impl_linux-64
  - gcc_linux-64
  - gdal
  - gds-tools
  - geographiclib
  - geopandas
  - geopandas-base
  - geopy
  - geos
  - geotiff
  - gflags
  - giflib
  - gitdb
  - gitpython
  - glog
  - gmp
  - gmpy2
  - google-api-core
  - google-api-python-client
  - google-auth
  - google-auth-httplib2
  - google-cloud-core
  - google-cloud-storage
  - google-crc32c
  - google-resumable-media
  - googleapis-common-protos
  - graphite2
  - grpcio
  - gxx
  - gxx_impl_linux-64
  - gxx_linux-64
  - h2
  - h5netcdf
  - h5py
  - harfbuzz
  - hdf4
  - hdf5
  - hpack
  - httplib2
  - hyperframe
  - icu
  - idna
  - imagecodecs
  - imageio
  - importlib-metadata
  - importlib_metadata
  - importlib_resources
  - ipykernel
  - ipython
  - ipython_pygments_lexers
  - isodate
  - jaraco.classes
  - jaraco.context
  - jaraco.functools
  - jdcal
  - jedi
  - jeepney
  - jinja2
  - jmespath
  - joblib
  - json-c
  - jsonschema
  - jsonschema-specifications
  - jupyter_client
  - jupyter_core
  - jxrlib
  - kaldi
  - kerchunk
  - kernel-headers_linux-64
  - keyring
  - keyutils
  - kiwisolver
  - krb5
  - lazy-loader
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libabseil
  - libaec
  - libarchive
  - libarrow
  - libarrow-acero
  - libarrow-dataset
  - libarrow-substrait
  - libavif16
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcap
  - libcblas
  - libclang-cpp20.1
  - libclang13
  - libcrc32c
  - libcublas
  - libcublas-dev
  - libcudnn
  - libcudnn-dev
  - libcudss
  - libcufft
  - libcufft-dev
  - libcufile
  - libcufile-dev
  - libcups
  - libcurand
  - libcurand-dev
  - libcurl
  - libcusolver
  - libcusolver-dev
  - libcusparse
  - libcusparse-dev
  - libde265
  - libdeflate
  - libdrm
  - libedit
  - libegl
  - libev
  - libevent
  - libexpat
  - libffi
  - libfreetype
  - libfreetype6
  - libgcc
  - libgcc-devel_linux-64
  - libgcc-ng
  - libgcrypt-lib
  - libgdal-core
  - libgdal-jp2openjpeg
  - libgfortran
  - libgfortran5
  - libgirepository
  - libgl
  - libglib
  - libglvnd
  - libglx
  - libgomp
  - libgoogle-cloud
  - libgoogle-cloud-storage
  - libgpg-error
  - libgrpc
  - libheif
  - libhwloc
  - libhwy
  - libiconv
  - libjpeg-turbo
  - libjxl
  - libkml
  - liblapack
  - liblapacke
  - libllvm20
  - liblzma
  - libmagma
  - libnetcdf
  - libnghttp2
  - libnl
  - libnpp
  - libnpp-dev
  - libnsl
  - libntlm
  - libnuma
  - libnvfatbin
  - libnvfatbin-dev
  - libnvjitlink
  - libnvjitlink-dev
  - libnvjpeg
  - libnvjpeg-dev
  - libopengl
  - libopentelemetry-cpp
  - libopentelemetry-cpp-headers
  - libparquet
  - libpciaccess
  - libpng
  - libpq
  - libprotobuf
  - libre2-11
  - librttopo
  - libsanitizer
  - libsecret
  - libsodium
  - libspatialite
  - libsqlite
  - libssh2
  - libstdcxx
  - libstdcxx-devel_linux-64
  - libstdcxx-ng
  - libsystemd0
  - libthrift
  - libtiff
  - libtorch
  - libudev1
  - libutf8proc
  - libuuid
  - libuv
  - libwebp-base
  - libxcb
  - libxcrypt
  - libxkbcommon
  - libxkbfile
  - libxml2
  - libxslt
  - libzip
  - libzlib
  - libzopfli
  - lightning
  - lightning-utilities
  - llvm-openmp
  - llvmlite
  - locket
  - lz4
  - lz4-c
  - lzo
  - mapclassify
  - markupsafe
  - mashumaro
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - minizip
  - mkl
  - ml4xcube
  - more-itertools
  - mpc
  - mpfr
  - mpmath
  - msal
  - msal_extensions
  - msgpack-python
  - multidict
  - multiurl
  - munkres
  - mypy_extensions
  - narwhals
  - nccl
  - ncurses
  - nest-asyncio
  - netcdf4
  - networkx
  - nlohmann_json
  - nsight-compute
  - nspr
  - nss
  - numba
  - numcodecs
  - numpy
  - oauthlib
  - ocl-icd
  - opencl-headers
  - openfst
  - openjpeg
  - openldap
  - openssl
  - optree
  - orc
  - packaging
  - pandas
  - parso
  - partd
  - patsy
  - pcre2
  - pexpect
  - pickleshare
  - pillow
  - pims
  - pip
  - pixman
  - pkginfo
  - pkgutil-resolve-name
  - planetary-computer
  - platformdirs
  - portalocker
  - proj
  - prometheus-cpp
  - prompt-toolkit
  - propcache
  - proto-plus
  - protobuf
  - psutil
  - pthread-stubs
  - ptyprocess
  - pure_eval
  - pyarrow
  - pyarrow-core
  - pyasn1
  - pyasn1-modules
  - pybind11
  - pybind11-global
  - pycairo
  - pycparser
  - pydantic
  - pydantic-core
  - pygments
  - pygobject
  - pyjwt
  - pyogrio
  - pyopenssl
  - pyparsing
  - pyproj
  - pyproject_hooks
  - pyside6
  - pysocks
  - pystac
  - pystac-client
  - python
  - python-box
  - python-build
  - python-dateutil
  - python-dotenv
  - python-fastjsonschema
  - python-installer
  - python-tzdata
  - python_abi
  - pytorch>2
  - pytorch-gpu>2
  - pytorch-lightning
  - pytz
  - pyu2f
  - pywavelets
  - pyyaml
  - pyzmq
  - qhull
  - qt6-main
  - rasterio
  - rav1e
  - rdma-core
  - re2
  - readline
  - rechunker
  - referencing
  - requests
  - requests-oauthlib
  - requests-toolbelt
  - rfc3339-validator
  - rioxarray
  - rpds-py
  - rsa
  - ruamel.yaml
  - ruamel.yaml.clib
  - s2n
  - s3fs
  - s3transfer
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - seaborn-base
  - secretstorage
  - semver
  - sen2nbar
  - setuptools
  - shapely
  - shellingham
  - six
  - sleef
  - slicerator
  - smmap
  - snappy
  - snuggs
  - sortedcontainers
  - soupsieve
  - spyndex
  - sqlite
  - stack_data
  - stackstac
  - statsmodels
  - svt-av1
  - sympy
  - sysroot_linux-64
  - tabulate
  - tbb
  - tblib
  - threadpoolctl
  - tifffile
  - tk
  - toml
  - tomli
  - tomlkit
  - toolz
  - torchaudio
  - torchmetrics
  - torchvision
  - torchvision-extra-decoders
  - tornado
  - tqdm
  - traitlets
  - triton
  - trove-classifiers
  - typing-extensions
  - typing-inspection
  - typing_extensions
  - tzdata
  - ujson
  - unicodedata2
  - uriparser
  - uritemplate
  - urllib3
  - virtualenv
  - wayland
  - wcwidth
  - wheel
  - wrapt
  - x265
  - xarray
  - xcb-util
  - xcb-util-cursor
  - xcb-util-image
  - xcb-util-keysyms
  - xcb-util-renderutil
  - xcb-util-wm
  - xcube
  - xcube-cds
  - xcube-sh
  - xcube-stac
  - xerces-c
  - xkeyboard-config
  - xmltodict
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxau
  - xorg-libxcomposite
  - xorg-libxcursor
  - xorg-libxdamage
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxfixes
  - xorg-libxi
  - xorg-libxrandr
  - xorg-libxrender
  - xorg-libxtst
  - xorg-libxxf86vm
  - xyzservices
  - yaml
  - yarl
  - zappend
  - zarr
  - zeromq
  - zfp
  - zict
  - zipp
  - zlib
  - zlib-ng
  - zstandard
  - zstd
  - pip:
      - global-land-mask
